# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 코로나19 확진자/완치자 사례 공유
email: kimhyuck777@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  코로나19 확진자 및 완치자들이 서로 사례를 나누며 불안감을 줄이고, 심리적인 안정감을 찾아보기 위해 만든 페이지입니다. 불확실한 정보의 확산을 막기 위해 일부 내용을 발췌하여 공유하거나 및 기사화하기를 원하지 않습니다. 공유되는 사연의 내용은 사연 당사자에게 저작권이 있습니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://see-mike-out.github.io/covid-empathy/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: "HyeokMKim"
github_username:  "see-mike-out"

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

minima:
  date_format: "%Y년 %-m월 %-d일"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
